name: story_app
description: "Story App for Dicoding Project"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# ---------- Packages ---------- #
dependencies:
  flutter:
    sdk: flutter
  logger: ^2.1.1
  
  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # ðŸŒ State Management
  provider: ^6.1.0

  # ðŸŒ Connections
  dio: ^5.4.0
  connectivity_plus: ^4.0.1

  # ðŸ”„ Navigation Web / Desktop
  go_router: ^13.2.0

  # ðŸ”„ Navigation Mobile App
  get: ^4.6.6

  # ðŸ”‘ Local Storage
  shared_preferences: ^2.2.2

  # ðŸ“¸ Image Picker
  image_picker: ^1.0.7 

  # ðŸŒ Localization & Formatting
  intl: ^0.18.0 

  # ðŸŽ¨ UI Enhancements
  cached_network_image: ^3.3.0
  

  # ðŸ”„ Background & Loading
  flutter_spinkit: ^5.2.0
  lottie: ^3.3.1

# ---------- End Packages ---------- #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# ---------- Local Assets ---------- #
  assets:
    - assets/
# ---------- End Flutter ---------- #

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
